const dict: Record<string, { en: string; ru: string; icon: string }> = {
  '车架': { en: 'Frame', ru: 'Рама', icon: '🔧' },
  '车斗': { en: 'Bucket', ru: 'Кузов', icon: '🛻' },
  '车轮': { en: 'Wheel', ru: 'Колесо', icon: '🛞' },
  '轮胎': { en: 'Tire', ru: 'Шина', icon: '🛞' },
  '刹车': { en: 'Brake', ru: 'Тормоз', icon: '🛑' },
  '制动': { en: 'Brake', ru: 'Тормоз', icon: '🛑' },
  '传动': { en: 'Drivetrain', ru: 'Трансмиссия', icon: '⛓️' },
  '链条': { en: 'Chain', ru: 'Цепь', icon: '⛓️' },
  '座椅': { en: 'Seat', ru: 'Сиденье', icon: '🪑' },
  '靠背': { en: 'Backrest', ru: 'Спинка', icon: '🪑' },
  '灯具': { en: 'Light', ru: 'Фара', icon: '💡' },
  '电气': { en: 'Electrical', ru: 'Электрика', icon: '⚡' },
  '轴承': { en: 'Bearing', ru: 'Подшипник', icon: '⚙️' },
  '轴套': { en: 'Bushing', ru: 'Втулка', icon: '⚙️' },
  '螺丝': { en: 'Screw', ru: 'Винт', icon: '🔩' },
  '紧固': { en: 'Fastener', ru: 'Крепеж', icon: '🔩' },
  '减震': { en: 'Shock', ru: 'Амортизатор', icon: '🔧' },
  '悬挂': { en: 'Suspension', ru: 'Подвеска', icon: '🔧' },
  '弹簧': { en: 'Spring', ru: 'Пружина', icon: '🪝' },
  '挡泥板': { en: 'Fender', ru: 'Крыло', icon: '🛡️' },
  '把手': { en: 'Handlebar', ru: 'Руль', icon: '🔄' },
  '后视镜': { en: 'Mirror', ru: 'Зеркало', icon: '🪞' },
  '电瓶': { en: 'Battery', ru: 'Аккумулятор', icon: '🔋' },
  '喇叭': { en: 'Horn', ru: 'Гудок', icon: '📢' },
  '配件': { en: 'Parts', ru: 'Запчасти', icon: '📦' },
  '脚踏': { en: 'Pedal', ru: 'Педаль', icon: '🦶' },
  '飞轮': { en: 'Flywheel', ru: 'Маховик', icon: '⚙️' },
  '轮毂': { en: 'Hub', ru: 'Ступица', icon: '🛞' },
  '大灯': { en: 'Headlight', ru: 'Фара', icon: '💡' },
  '尾灯': { en: 'Taillight', ru: 'Задний фонарь', icon: '🔴' },
  '转向灯': { en: 'Turn Signal', ru: 'Поворотник', icon: '↔️' },
  '螺栓': { en: 'Bolt', ru: 'Болт', icon: '🔩' },
  '螺母': { en: 'Nut', ru: 'Гайка', icon: '🔩' },
  '垫片': { en: 'Washer', ru: 'Шайба', icon: '🔩' },
  '辐条': { en: 'Spoke', ru: 'Спица', icon: '🛞' },
  '前叉': { en: 'Fork', ru: 'Вилка', icon: '🔧' },
  '车圈': { en: 'Rim', ru: 'Обод', icon: '🛞' },
  '刹车片': { en: 'Brake Pad', ru: 'Тормозная колодка', icon: '🛑' },
  '刹车线': { en: 'Brake Cable', ru: 'Трос тормоза', icon: '🛑' },
  '牙盘': { en: 'Crank', ru: 'Шатун', icon: '⚙️' },
  '中轴': { en: 'Bottom Bracket', ru: 'Каретка', icon: '⚙️' },
  '座垫': { en: 'Saddle', ru: 'Сиденье', icon: '🪑' },
  '变速箱': { en: 'Gearbox', ru: 'Коробка передач', icon: '⚙️' },
  '离合器': { en: 'Clutch', ru: 'Сцепление', icon: '⚙️' },
  '化油器': { en: 'Carburetor', ru: 'Карбюратор', icon: '🔧' },
  '火花塞': { en: 'Spark Plug', ru: 'Свеча', icon: '⚡' },
  '发动机': { en: 'Engine', ru: 'Двигатель', icon: '🏍️' },
  '排气管': { en: 'Exhaust', ru: 'Выхлоп', icon: '💨' },
  '油箱': { en: 'Fuel Tank', ru: 'Бензобак', icon: '⛽' },
  '车把': { en: 'Handlebar', ru: 'Руль', icon: '🔄' },
  '支架': { en: 'Stand', ru: 'Подставка', icon: '🔧' },
  '车筐': { en: 'Basket', ru: 'Корзина', icon: '🧺' },
  '里程表': { en: 'Odometer', ru: 'Одометр', icon: '📟' },
  '牌照架': { en: 'Plate Holder', ru: 'Рамка номера', icon: '📋' },
  '工具箱': { en: 'Toolbox', ru: 'Ящик', icon: '🧰' },
  '货架': { en: 'Rack', ru: 'Стеллаж', icon: '📦' },
  '皮带': { en: 'Belt', ru: 'Ремень', icon: '🔄' },
  '油封': { en: 'Oil Seal', ru: 'Сальник', icon: '🛡️' },
  '滤清器': { en: 'Filter', ru: 'Фильтр', icon: '🔍' },
  '散热器': { en: 'Radiator', ru: 'Радиатор', icon: '❄️' },
  '电机': { en: 'Motor', ru: 'Мотор', icon: '⚡' },
  '控制器': { en: 'Controller', ru: 'Контроллер', icon: '🎛️' },
  '充电器': { en: 'Charger', ru: 'Зарядное', icon: '🔌' },
  '刹车鼓': { en: 'Brake Drum', ru: 'Тормозной барабан', icon: '🛑' },
  '刹车盘': { en: 'Brake Disc', ru: 'Тормозной диск', icon: '🛑' },
  '刹把': { en: 'Brake Lever', ru: 'Ручка тормоза', icon: '🛑' },
  '座管': { en: 'Seatpost', ru: 'Подседел', icon: '🪑' },
  '坐垫': { en: 'Cushion', ru: 'Подушка', icon: '🪑' },
  '前灯': { en: 'Headlight', ru: 'Фара', icon: '💡' },
  '螺钉': { en: 'Screw', ru: 'Винт', icon: '🔩' },
  '卡簧': { en: 'Circlip', ru: 'Стопор', icon: '🔩' },
  '减震器': { en: 'Shock Absorber', ru: 'Амортизатор', icon: '🔧' },
  '避震': { en: 'Shock', ru: 'Амортизатор', icon: '🔧' },
  '大梁': { en: 'Beam', ru: 'Балка', icon: '🔧' },
  '靠垫': { en: 'Cushion', ru: 'Подушка', icon: '🪑' },
  '反光镜': { en: 'Reflector', ru: 'Отражатель', icon: '🪞' },
  '链轮': { en: 'Sprocket', ru: 'Звездочка', icon: '⚙️' },
  '曲柄': { en: 'Crank Arm', ru: 'Шатун', icon: '⚙️' },
  '滚珠': { en: 'Ball Bearing', ru: 'Шарикоподшипник', icon: '⚙️' },
  '轮轴': { en: 'Axle', ru: 'Ось', icon: '🛞' },
  '内胎': { en: 'Inner Tube', ru: 'Камера', icon: '🛞' },
  '外胎': { en: 'Outer Tire', ru: 'Покрышка', icon: '🛞' },
  '轮圈': { en: 'Rim', ru: 'Обод', icon: '🛞' },
  '高压包': { en: 'Ignition Coil', ru: 'Катушка зажигания', icon: '⚡' },
  '继电器': { en: 'Relay', ru: 'Реле', icon: '⚡' },
  '保险丝': { en: 'Fuse', ru: 'Предохранитель', icon: '⚡' },
  '开关': { en: 'Switch', ru: 'Выключатель', icon: '🔘' },
  '线束': { en: 'Wiring Harness', ru: 'Жгут проводов', icon: '🔌' },
  '后桥': { en: 'Rear Axle', ru: 'Задний мост', icon: '🔧' },
  '差速器': { en: 'Differential', ru: 'Дифференциал', icon: '⚙️' },
  '半轴': { en: 'Half Shaft', ru: 'Полуось', icon: '🔧' },
  '万向节': { en: 'Universal Joint', ru: 'Кардан', icon: '🔧' },
  '油管': { en: 'Oil Pipe', ru: 'Маслопровод', icon: '🔧' },
  '油泵': { en: 'Oil Pump', ru: 'Маслонасос', icon: '🔧' },
  '水泵': { en: 'Water Pump', ru: 'Водяной насос', icon: '💧' },
  '水箱': { en: 'Radiator', ru: 'Радиатор', icon: '💧' },
  '风扇': { en: 'Fan', ru: 'Вентилятор', icon: '🌀' },
  '皮带轮': { en: 'Pulley', ru: 'Шкив', icon: '🔄' },
  '张紧轮': { en: 'Tensioner', ru: 'Натяжитель', icon: '🔄' },
  '密封圈': { en: 'Seal Ring', ru: 'Уплотнение', icon: '🛡️' },
  '密封垫': { en: 'Gasket', ru: 'Прокладка', icon: '🛡️' },
  'O型圈': { en: 'O-Ring', ru: 'Кольцо', icon: '🛡️' },
  '活塞': { en: 'Piston', ru: 'Поршень', icon: '🔧' },
  '活塞环': { en: 'Piston Ring', ru: 'Кольцо поршня', icon: '🔧' },
  '缸体': { en: 'Cylinder', ru: 'Цилиндр', icon: '🔧' },
  '缸盖': { en: 'Cylinder Head', ru: 'Головка цилиндра', icon: '🔧' },
  '气门': { en: 'Valve', ru: 'Клапан', icon: '🔧' },
  '凸轮轴': { en: 'Camshaft', ru: 'Распредвал', icon: '⚙️' },
  '曲轴': { en: 'Crankshaft', ru: 'Коленвал', icon: '⚙️' },
  '连杆': { en: 'Connecting Rod', ru: 'Шатун', icon: '🔧' },
};

export function translateZh(zh: string): { en: string; ru: string; icon: string } {
  let en = '';
  let ru = '';
  let icon = '📦';

  for (const [keyword, trans] of Object.entries(dict)) {
    if (zh.includes(keyword)) {
      if (!en) en = trans.en;
      if (!ru) ru = trans.ru;
      if (icon === '📦') icon = trans.icon;
    }
  }

  return { en, ru, icon };
}
